services:
  bot:
    build: .
    container_name: solo_leveling_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data_storage:/app/data_storage   # только для db.sql
    environment:
      - DB_PATH=/app/data_storage/db.sql